AppBundle\Entity\Publisher:
    type: entity
    table: publishers
    repositoryClass: AppBundle\Repository\PublisherRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        books:
            targetEntity: AppBundle\Entity\Book
            mappedBy: publisher
    lifecycleCallbacks: {  }
